name: gruve_app

description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.10.1
  sms_autofill: ^2.3.0
  camera: ^0.11.0+2
  http: ^0.13.6
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.2
  flutter_dotenv: ^5.1.0
  dropdown_button2: ^2.3.9
  cupertino_icons: ^1.0.8
  country_picker: ^2.0.27
  image_picker: ^1.2.1
  permission_handler: ^12.0.1
  fl_chart: ^0.66.0
  provider: ^6.0.0
  get: ^4.6.6
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  sqflite: ^2.3.0
  google_mlkit_face_detection: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/splash_screen_logo/
    - assets/fonts/
    - assets/auth/icons/
    - assets/videos/
    - assets/button/
    - assets/home/
    - assets/search_screen_images/
    - assets/notification_images/
    - assets/menu_drawer/
    - assets/performance reel/
    - assets/saved/
    - assets/blocked/
    - assets/message_bg/
    - assets/contact_us/
    - assets/subscription/
    - assets/slide_bar/
    - assets/story/
    - assets/message/
    - assets/flash_sales/
    - assets/3 dots/
    - assets/share/
    - assets/complete_profile/
    - assets/user_profile_grid/
    - assets/icons/
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-VariableFont_wght.ttf
        - asset: assets/fonts/Raleway/Raleway-Italic-VariableFont_wght.ttf
          style: italic
    - family: Syncopate
      fonts:
        - asset: assets/fonts/Syncopate/Syncopate-Regular.ttf
        - asset: assets/fonts/Syncopate/Syncopate-Bold.ttf
    - family: montserrat
      fonts:
        - asset: assets/fonts/montserrat/MontserratAlternates-Bold.ttf
        - asset: assets/fonts/montserrat/MontserratAlternates-Regular.ttf
